spring.application.name=Streak

# DataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/streak
spring.datasource.username=ureca
spring.datasource.password=ureca

# Session Persistence
server.servlet.session.persistent=false
#server.servlet.session.timeout=60m

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# schema.sql / data.sql 자동 실행 (앱 재시작마다 테이블을 초기화하고 더미 데이터를 다시 채움)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# junit test logging
# logging.level.com.example=DEBUG